version: "3.7"

services:
  redis:
    container_name: workout-redis
    image: redis
    command: redis-server --port 6379
    hostname: redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6379:6379"
  nginx:
    container_name: workout-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
  backend:
    container_name: workout-backend
    build: .
    ports:
        - "8000:8000"
    depends_on:
      - redis
